---
title: "R Notebook"
output: html_notebook
---


```{r}
library(dplyr)
library(tidyr)
library(stringr)
library(lubridate)
```



```{r}
#查看前6筆
head(StuDF)
#查看後6筆
tail(StuDF)
```

```{r}
##slice:切割資料
StuDF
slice(StuDF,1:3) #第1筆到第3筆資料(冒號代表連續選取)
slice(StuDF,4:5)
slice(StuDF,n()) #計算目前所使用的dataframe有多少資料
slice(StuDF,(n()-1):n()) #第n-1筆到第n筆(倒數2筆)
```

```{r}
StuDF
slice(StuDF,-5:-7) #567不要
slice(StuDF,-(5:7))#較好寫法
slice(StuDF,c(-5,-6,-7))
```

```{r}
#選出1 4 8
slice(StuDF,c(1,4,8))
```

```{r}
library(readr)
#匯入資料
collegeData <- read_csv("https://raw.githubusercontent.com/tpemartin/github-data/master/103_student.csv")

#檢查資料結構
str(collegeData)

#取出所需資料
slice(collegeData, c(1:4, (n()-1:n()), 101:110))
```


```{r}
StuDF
mutate(StuDF,
       調分後成績=成績+10)
transmute(StuDF,
       調分後成績=成績+10) # 不保留其他變數:新的dataframe只有新創的欄位
```

```{r}
#若要更動原data frame內容，記得要回存
StuDF <- 
  mutate(StuDF,
       調分後成績=成績+10)
```

```{r}
#從list角度看物件，創造新的欄位
StuDF$調分後成績 <-
  StuDF$成績+10
```

```{r}
#在collegeData:
##新增變數男生及女生,其值為「一到四年級」所有男生及女生的加總。（男生使用dplyr, 女生不使用dplyr）

#男生
collegeData <- mutate(collegeData, 男生 = collegeData[[5]]+collegeData[[7]]+collegeData[[9]]+collegeData[[11]])

#女生
collegeData$女生 <- collegeData[[6]]+collegeData[[8]]+collegeData[[10]]+collegeData[[12]]

#新增變數男女生比，其值為前述男生/女生。
collegeData$男女生比 <- collegeData$男生/collegeData$女生
```

```{r}
##可以一次創很多變數(注意順序)
collegeData <- mutate(collegeData, 
                      男生 = collegeData[[5]]+collegeData[[7]]+collegeData[[9]]+collegeData[[11]],
                      女生 = collegeData[[6]]+collegeData[[8]]+collegeData[[10]]+collegeData[[12]],
                      男女生比 = 男生/女生)

```

```{r}
#summarise:只算總和的
#input,optput都是dataframe
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

```

```{r}
#變成mutate:每列都分別算出來
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
```

```{r}
#若老師的調分為原始成績加上「最高最低分差距除以5」，請產生調分成績:
mutate(StuDF, 調分成績 = 成績+(max(成績)-min(成績))/5)

```


```{r}
##select:選擇變數
StuDF
mutate(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績)) -> StuDF2
```

```{r}
StuDF2
names(StuDF2) #顯示物件內的元素名稱
select(StuDF2,
       姓名,學號,成績,調分後成績) #要選擇欄位放後面
select(StuDF2,
       -次序,-性別,-最高分,-最低分) #負號代表不選
```

```{r}
#綜合select
select(StuDF2,
       次序,性別,
       contains("最"))

select(StuDF2,
       -次序,-性別,
       -contains("最"))
```

```{r}
#選出collegeData中所有男生變數
select(collegeData,
       contains("男生"))
```


```{r}
##filter
#Logical predicates
StuDF
# logical vector
logiChoose <- c(
  F,F,F,T,T,F,T,F
)
# 使用logical vector選擇所要觀測值"女"
StuDF[logiChoose,] #取出為true的

#自訂predicates
StuDF$性別=="女" # logical predicate

logiChoose <- StuDF$性別=="女"
StuDF[logiChoose,]
```

```{r}
#使用with與slice
#可顯示向量元素為真的位置
logiChoose
which(logiChoose)
slice(
  StuDF,which(logiChoose)
)
```

```{r}
# relational operators
StuDF$性別=="女" 
StuDF$成績>60

# combined with logical operator
(StuDF$性別=="女" & StuDF$成績>60) -> logiChoose2
logiChoose2

StuDF[logiChoose2,]
```


```{r}
#使用filter
filter(StuDF,
       性別=="女")
filter(StuDF,
       (性別=="女" & 成績>60))
filter(StuDF,
       性別=="女",
       成績>60) # 多個AND條件可用,分隔
```

```{r}
##請計算StuDF中:
#女性平均成績，最高分，最低分
StuDF_G <- filter(StuDF,
       性別=="女")
summarise(StuDF_G,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

#女性平均成績，最高分，最低分

##依以下各別情境，選出collegeData中符合情境的觀測值：
#縣市名稱為“30 臺北市”
filter(collegeData,
       collegeData[[21]] == "30 臺北市")

#縣市名稱為“30 臺北市”或“01 新北市”。（使用OR|或belong to%in%）
filter(collegeData,
       collegeData[[21]] == "30 臺北市" | collegeData[[21]] == "01 新北市")

```


```{r}
# 縣市名稱為“30 臺北市”
filter(collegeData,
       縣市名稱=="30 臺北市")
# 縣市名稱為“30 臺北市”或“01 新北市”
filter(collegeData,
       縣市名稱=="30 臺北市" | 縣市名稱=="01 新北市")
```

```{r}
## group_by
# 直接下group_by:新的dataframe
group_by(StuDF,
         性別) -> StuDF_by性別

# 使用grouped data frame
summarise(StuDF_by性別,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))

# 使用ungrouped data frame
summarise(StuDF,
        平均成績=mean(成績),
        最高分=max(成績),
        最低分=min(成績))
```


```{r}
## 男女調分不同:分不同group
# 各加其群組之「最高減最低分除以5」
mutate(
  StuDF_by性別,
  最高分=max(成績),
  最低分=min(成績),
  調分大小=(最高分-最低分)/5,
  調分後成績=成績+調分大小
) -> StuDF_依性別調分
StuDF_依性別調分
```

```{r}
# 依性別&成績分
# 依性別及成績是否大於75分：
group_by(StuDF,
         性別,
         (成績>75)) -> StuDF_by性別成績 #分群條件以逗號分隔

summarise(StuDF_by性別成績,
          平均成績=mean(成績),
          人數=n())
```

```{r}
##ungroup
ungroup(StuDF_依性別調分) -> 
  StuDF_調分後
```

```{r}
##計算collegeData中不同縣市名稱,體系別,等級別的一年級男生及一年級女生總數（使用sum）和學校數目。
#分群不同縣市名稱及體系別
collegeData_group <- group_by(collegeData,
                              縣市名稱,
                              體系別,
                              等級別)


#計算
summarise(collegeData_group,
          一年級男生總數 = sum(一年級男生),
          一年級女生總數 = sum(一年級女生),
          學校數目 = n())

summarise(collegeData_group,
          一年級男生總數 = sum(一年級男生),
          一年級女生總數 = sum(一年級女生),
          學校數目 = length(unique(學校名稱))
```
### pipe
```{r}
#不用pipe
group_by(StuDF,
         性別) -> StuDF_by性別

mutate(
  StuDF_by性別,
  最高分=max(成績),
  最低分=min(成績),
  調分大小=(最高分-最低分)/5,
  調分後成績=成績+調分大小
) -> StuDF_依性別調分

ungroup(StuDF_依性別調分) -> 
  StuDF_調分後
```

##使用pipe
#原則1:%>% 把它左邊（LHS）的物件流入它右邊（RHS）函數的argument第一個位置
```{r}
s# group_by(StuDF,
#          性別) -> StuDF_by性別
StuDF %>% group_by(
         性別) -> StuDF_by性別

# mutate(
#   StuDF_by性別,
#   最高分=max(成績),
#   最低分=min(成績),
#   調分大小=(最高分-最低分)/5,
#   調分後成績=成績+調分大小
# ) -> StuDF_依性別調分

StuDF_by性別 %>%
mutate(
  最高分=max(成績),
  最低分=min(成績),
  調分大小=(最高分-最低分)/5,
  調分後成績=成績+調分大小
) -> StuDF_依性別調分


# ungroup(StuDF_依性別調分) -> 
#   StuDF_調分後
StuDF_依性別調分 %>% ungroup() -> 
  StuDF_調分後
```

#原則3:%>% 可進行串接，則下一個%>%會以上個函數輸出結果當做新的LHS物件
```{r}

StuDF %>% group_by(
         性別)  %>%
mutate(
  最高分=max(成績),
  最低分=min(成績),
  調分大小=(最高分-最低分)/5,
  調分後成績=成績+調分大小
)  %>% ungroup() -> 
  StuDF_調分後
```

```{r}
#將collegeData，
#依等級別,縣市名稱分群後,

collegeData %>%
  group_by(等級別,縣市名稱) %>%
  summarise(一年級男女比例 = sum(一年級男生)/ sum(一年級女生)) %>%
  summarise(等級別=which.max(一年級男女比例),
            縣市別=which.max(一年級男女比例))

#計算一年級男/女生比例後,

#找出男女生比例最高的等級別,縣市名稱組合。
```

```{r}
load(url("https://www.dropbox.com/s/duh5aaqgl2f5m3z/loopTranscriptData.Rda?raw=1"))
```

```{r}
#計算每位學生每學期的平均成績。

#計算每位學生每學期學分數在必/選/通 三類的學分數比重。

#學屆為100（即100學年入學）的學生，各系學生在學所修總學分數之中位數，何系最高？
```

























