---
title: "每週一圖作業_1104"
output: html_document
params:
  組員: ["林書玉"]  
  學號: ["410575010"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}
library(tidyverse)

#讀取原始資料
load(url("https://github.com/tpemartin/course-108-1-inclass-datavisualization/blob/master/%E4%BD%9C%E5%93%81%E5%B1%95%E7%A4%BA/homework3/graphData_homework3_019.Rda?raw=true"))

graphData[[1]]
names(graphData)[[1]] <- "rawdata"
names(graphData)

#選擇需要的資料
graphData$rawdata %>%
  mutate(`師生比` = `教師數`/`學生數`) %>%
  filter(`科系名稱` == "經濟學系",
         `日間∕進修別` == "D 日",
         `等級別` == "B 學士",
         `體系別` == "1 一般") %>%
  select(`學校名稱`, `科系名稱`, `學生數`, `教師數`, `師生比`) -> graphData$newdata
  

```