---
title: "data_cleaning_1112"
output: html_document
params:
  組員: ["林書玉"]  
  學號: ["410575010"]
---

#### 環境設定

以下為老師執行時一定會存在的環境設定
```{r basic setup, message=FALSE, echo=TRUE, eval=T}
rm(list=ls())
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(colorspace); library(grDevices); library(shiny); library(shinyjs); library(scales)
library(tidyr); library(showtext); library(tidyverse); library(colorspace)

#font_add("QYuan","cwTeXQYuan-Medium.ttf") # 新增字體
showtext_auto(enable=TRUE) #啟用字體
theme_set(theme_classic())
knitr::opts_chunk$set(fig.align='center', fig.showtext=T)
```

#### 資料處理
  
```{r data cleaning, echo=TRUE, eval=T}

#讀取原始資料
library(readxl)
read_excel("C:/Users/user/Desktop/R/course-108-1-inclass-datavisualization/BD_data.xlsx") -> BD_data

graphData <- list()

#reshape data
BD_data %>%
gather(`聯繫`, `拜訪`, `一次提案`, `二次提案`, `簽約`,
       key = "階段", value = "數量") %>%
  mutate(階段 = as.factor(階段),
           時間 = as.character(時間) )-> graphData$BD_data

#重新排序level順序
graphData$BD_data$階段 <- factor(graphData$BD_data$階段, levels = c("簽約", "二次提案", "一次提案", "拜訪", "聯繫"))

graphData$BD_data$階段
```








