---
title: "Untitled"
author: "ShuYu"
date: "2019/10/23"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr); library(stringr); library(ggplot2); library(plotly); library(lubridate); library(readr); library(tidyr); library(showtext)
```

```{r}
library(readr)
library2014 <- read_csv("https://www.dropbox.com/s/999hy0u1y98y6ep/library2014.csv?dl=1")
```

```{r}
library2014 %>%
  mutate(
    學院=reorder(學院,學號,length,order=T),
    讀者年級=reorder(讀者年級,讀者年級, order=T)
  ) -> library2014

graphList <- list()

library2014 %>% 
  ggplot()-> graphList$圖書_ggplotOnly

graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院), fill="#5A99B3", width=0.7
    )
```

```{r}
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院,fill=讀者年級), width=0.7
  )
```

```{r}
graphList$圖書_ggplotOnly+
  geom_bar(
    aes(x=學院) # 預設 stat="count"
  )
```

```{r}
graphList$圖書_ggplotOnly +
  stat_count(              #stat_count
    aes(x=學院), 
    geom="bar"             #geom_bar內訂會取count來當y
  )
```

```{r}
graphList$圖書_ggplotOnly +
  stat_count(
    aes(x=學院,y=stat(prop)), #改成畫比例
    geom="bar" # geom_bar內訂會取 count來當y
  )
```

```{r}
#改成全校是一個group
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") #group
  )+
  stat_count(
    aes(
      x=學院,
      y=stat(prop), group="全校",
      label=round(stat(prop),digits=2)), #算完這3個mapping會丟給geom_text
    geom="text",
    color="white", nudge_y=0.2 #nudge無法在stat_count物件作用
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )
```

```{r}
#override stat
graphList$圖書_ggplotOnly +
  geom_bar(
    aes(x=學院, y=stat(prop), group="全校") 
  )+
  geom_text(
    aes(
      x=學院,
      y=stat(prop), group="全校",
      label=round(stat(prop),digits=2)),
    stat="count",
    color="white",nudge_y=-0.01 #從geom_text角度nudge就可以使用
  )+
  labs(
    title="各院借閱人次佔總人次比",x="",y=""
  )
```

```{r}
df_x <- data.frame(
  x=rnorm(500,mean=2,sd=1)
)
df_x %>%
  ggplot(aes(x=x))+
  geom_histogram(
    aes(y=stat(density)) #更改bin為整體機率
  )+
  stat_function(
    fun=dnorm, args = list(mean=2, sd=1) # dnorm 為常態分配density函數 
                                         #用list寫其他參數設定
  )
```


```{r}
market_demand <- function(x, a=1, b=-1){
  return(a+b*x)
}

market_supply <- function(x, a=0, b=1){
  return(a+b*x)
}

df_grids <- 
  data.frame(
    x=seq(0,1,by=0.2)) #產生序列 by:間距

df_grids %>%
  ggplot(aes(x=x))+    #產生一個畫布，x跟著之前設定的dataframe
  stat_function(
    fun="market_demand"
  )+
  stat_function(
    fun="market_supply"
  )+
  scale_y_continuous(
    limits = c(0,1)
  )+
  labs(
    x="Quantity", y="Price"
  ) -> graphList$demand_supply

graphList$demand_supply
```

































