---
title: "課堂練習20191030"
author: "ShuYu"
date: "2019/10/30"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
df0 <- data.frame(
  x=c(1,2,1,3,2),
  y=c(2,3,1,2,4),
  label=c("a","b","c","d","e")
)
df0 %>%
  ggplot(aes(x=x,y=y))+
  geom_label(
    aes(label=label), fill="pink"
    )-> plotbase0

list_graphs <- list()

plotbase0+geom_line()+labs(title="geom_line") -> #由小到大連
  list_graphs$geom_line

plotbase0+geom_path()+labs(title="geom_path") -> #依給定順序連
  list_graphs$geom_path

ggpubr::ggarrange(
  list_graphs$geom_line, list_graphs$geom_path
)
```


```{r}
ggplot()+theme_linedraw()+
  scale_x_continuous(limits=c(0,6),breaks=0:6,
                     expand=expand_scale(add=c(0,0)))+     #底線增加多少空間
  scale_y_continuous(limits=c(0,6),breaks=0:6,
                     expand=expand_scale(mult = c(0,0))) -> #expand:設定留白
  myGrids

myGrids
```

```{r}
list_geometryData <- list()
list_geometryData$points <- 
  rbind(
    c(1,5),
    c(2,1),
    c(5,1),
    c(5,5)) 
```


```{r}
list_geometryData$points %>%
  as.data.frame() 
```

```{r}
myGrids +
  geom_point(
    data=as.data.frame(list_geometryData$points),
    aes(x=V1,y=V2)
  ) -> list_graphs$point

myGrids +
  geom_path(
    data=as.data.frame(list_geometryData$points),
    aes(x=V1,y=V2)
  ) -> list_graphs$path

myGrids +
  geom_polygon(
    data=as.data.frame(list_geometryData$points),
    aes(x=V1,y=V2)
  ) -> list_graphs$polygon

ggpubr::ggarrange(
  list_graphs$point, list_graphs$path, list_graphs$polygon,
  ncol=3
)
```


```{r}
library(readr)
df_geo_northTW <- read_csv("https://www.dropbox.com/s/6uljw24zkyj7avs/df_geo_northTW.csv?dl=1")
```

```{r}
df_geo_northTW %>%
  filter(COUNTYNAME == "新北市") %>%
  ggplot(aes(x = x, y = y))+
  geom_polygon()+
  theme_linedraw()

#可是有台北市??
#要在原本資料創造sub_id
```


```{r}
list_graphs$polygon
```

```{r}
#產生洞
list_geometryData$hole <-
  rbind(
    c(2,4),
    c(3,2),
    c(4,3)
  )

list_geometryData$points %>%
  as.data.frame() -> df_part1
list_geometryData$hole %>%
  as.data.frame() -> df_part2

df_part1 %>%
  mutate(
    sub_id=1
  ) -> df_part1

df_part2 %>%
  mutate(
    sub_id=2
  ) -> df_part2

bind_rows(
  df_part1,
  df_part2
) -> df_all

df_all %>%
  mutate(
    group_id="A"
  ) -> df_all

myGrids +
  geom_polygon(
    data=df_all,
    aes(x=V1,y=V2, group=group_id, subgroup=sub_id) #要有group id 才能有sub id
  )
```

```{r}
df_geo_northTW %>%
  filter(COUNTYNAME == "新北市") %>%
  ggplot(aes(x = x, y = y))+
  geom_polygon()+
  theme_linedraw()


#一個變數保留新北市和臺北市邊界
df_geo_northTW %>%
  filter(COUNTYNAME %in% c("臺北市", "新北市")) %>%
  mutate(group_id = "新北市")

#一個保留sub id
df_ntp 

```

```{r}
library(magick)

image_read("https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/2450df20386177.562ea7d13f396.jpg") -> taipei101
```

```{r}
taipei101 %>%
  image_info() -> taipei101info

taipei101info
```

```{r}
# 檢視圖片高寬比
taipei101info$height/taipei101info$width -> img_asp # image aspect ratio
img_asp
```

```{r}
theme_linedraw()+
  theme(
    panel.background = element_rect(fill="cyan4")
  ) -> list_graphs$theme_backgroundCheck

# 圖片底色非透明
taipei101 %>%
  image_ggplot()+
  list_graphs$theme_backgroundCheck
```

```{r}
ggplot()+theme_linedraw()+
  theme(
    panel.background = element_rect(fill="cyan4")
  )
```

```{r}
image_fill(taipei101, "transparent", point = "+100+100", fuzz = 0) %>% # fuzz=對邊界定義模糊度 %>% # 這裡的fuzz完全沒有模糊地帶會有留白
    image_ggplot()+list_graphs$theme_backgroundCheck
```

```{r}
image_fill(taipei101,"transparent", point = "+100+100", fuzz=30) %>% #point:取樣一個白色點 #fuzz:邊界模糊度
    image_ggplot()+list_graphs$theme_backgroundCheck
```

```{r}
image_fill(taipei101,"transparent", point = "+100+100", fuzz=30) -> 
  taipei101transparent

taipei101transparent %>%
  as.raster() ->
  raster_taipei101
```

```{r}
loc <- c(lon=121.5622782,lat=25.0339687) # Taipei101 經緯度
imgWidth <- 0.13 # Taipei101在圖片佔寬

list_graphs$northTW +
  annotation_raster(raster_taipei101,
                    loc[1]-imgWidth/2,loc[1]+imgWidth/2,
                    loc[2]-imgWidth/2*img_asp,loc[2]+imgWidth/2*img_asp)
```

```{r}
loc <- c(lon=121.5622782,lat=25.0339687) # Taipei101 經緯度
imgWidth <- 0.13 # Taipei101在圖片佔寬

list_graphs$northTW +
  annotation_raster(raster_taipei101,
                    loc[1]-imgWidth/2,loc[1]+imgWidth/2,
                    loc[2]-imgWidth/2*img_asp,loc[2]+imgWidth/2*img_asp)
```

















